# Generated by Django 3.2.12 on 2023-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
